/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DPyzuqEkeXF
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { JSX, SVGProps } from "react";
import Link from "next/link";
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { ModeToggle } from "../ui/toggledarkmode";
import Image from "next/image";
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuIndicator,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  NavigationMenuViewport,
} from "@/components/ui/navigation-menu";
import React from "react";

const components: { title: string; href: string; description: string }[] = [
  {
    title: "Alert Dialog",
    href: "/docs/primitives/alert-dialog",
    description:
      "A modal dialog that interrupts the user with important content and expects a response.",
  },
];

export default function V0Navbar() {
  return (
    <header className="flex fixed h-16 w-full items-center  z-50 justify-between px-4 md:px-6 border bg-slate-100 dark:bg-black">
      <Image src="/logo.png" width={100} height={100} alt="MMA Logo" />

      <nav className="hidden items-center gap-6 md:flex">
        <NavigationMenu>
          <NavigationMenuList>
            <NavigationMenuItem>
              <Link href="/" className="text-lg font-medium">
                Home
              </Link>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>

        <NavigationMenu>
          <NavigationMenuList>
            <NavigationMenuItem>
              <NavigationMenuTrigger className="text-lg">
                Mixed Martial Art
              </NavigationMenuTrigger>
              <NavigationMenuContent>
                <ul className="w-48 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white">
                  <li className="w-full px-4 py-2 border-b border-gray-200 rounded-t-lg dark:border-gray-600">
                    <a href="/product">Boxing Glove</a>
                  </li>
                  <li className="w-full px-4 py-2 border-b border-gray-200 dark:border-gray-600">
                    <a href="/product">MMA Gloves</a>
                  </li>
                  <li className="w-full px-4 py-2 border-b border-gray-200 dark:border-gray-600">
                    <a href="/product">Dumbell</a>
                  </li>
                </ul>
              </NavigationMenuContent>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>

        <NavigationMenu>
          <NavigationMenuList>
            <NavigationMenuItem>
              <NavigationMenuTrigger className="text-lg">
                Fitness
              </NavigationMenuTrigger>
              <NavigationMenuContent>
                <ul className="w-48 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white">
                  <li className="w-full px-4 py-2 border-b border-gray-200 rounded-t-lg dark:border-gray-600">
                    <a href="/product">Dip Bar</a>
                  </li>
                  <li className="w-full px-4 py-2 border-b border-gray-200 dark:border-gray-600">
                    <a href="/product">Pull Up Bar</a>
                  </li>
                  <li className="w-full px-4 py-2 border-b border-gray-200 dark:border-gray-600">
                    <a href="/product">Dumbell</a>
                  </li>
                </ul>
              </NavigationMenuContent>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>

        <NavigationMenu>
          <NavigationMenuList>
            <NavigationMenuItem>
              <NavigationMenuTrigger className="text-lg">
                Calisthenic
              </NavigationMenuTrigger>
              <NavigationMenuContent>
                <ul className="w-48 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white">
                  <li className="w-full px-4 py-2 border-b border-gray-200 rounded-t-lg dark:border-gray-600">
                    <a href="/product">Dip Bar</a>
                  </li>
                  <li className="w-full px-4 py-2 border-b border-gray-200 dark:border-gray-600">
                    <a href="/product">Pull Up Bar</a>
                  </li>
                  <li className="w-full px-4 py-2 border-b border-gray-200 dark:border-gray-600">
                    <a href="/product">Dumbell</a>
                  </li>
                </ul>
              </NavigationMenuContent>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>

        <NavigationMenu>
          <NavigationMenuList>
            <NavigationMenuItem>
              <NavigationMenuTrigger className="text-lg">
                Boxing
              </NavigationMenuTrigger>
              <NavigationMenuContent>
                <ul className="w-48 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg dark:bg-gray-700 dark:border-gray-600 dark:text-white">
                  <li className="w-full px-4 py-2 border-b border-gray-200 rounded-t-lg dark:border-gray-600">
                    <a href="/product">Dip Bar</a>
                  </li>
                  <li className="w-full px-4 py-2 border-b border-gray-200 dark:border-gray-600">
                    <a href="/product">Pull Up Bar</a>
                  </li>
                  <li className="w-full px-4 py-2 border-b border-gray-200 dark:border-gray-600">
                    <a href="/product">Dumbell</a>
                  </li>
                </ul>
              </NavigationMenuContent>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>

        <NavigationMenu>
          <NavigationMenuList>
            <NavigationMenuItem>
              <Link href="/brands" className="text-lg font-medium">
                Brands
              </Link>
            </NavigationMenuItem>
          </NavigationMenuList>
        </NavigationMenu>
      </nav>

      <div className="flex items-center gap-4">
        <Sheet>
          <SheetTrigger asChild>
            <Button variant="ghost" size="icon" className="md:hidden">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle navigation</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="right" className="w-[200px]">
            <nav className=" flex flex-col items-center  gap-4 p-4">
              <NavigationMenu>
                <NavigationMenuList>
                  <NavigationMenuItem className="bg-background border border-black rounded">
                    <Image
                    src="/navwow.jpg"
                    height={200}
                    width={200}
                    alt="Logo"></Image>
                    <p>mager cuk lanjut nanti, liat mode dekstop aja</p>
                    <button className="bg-black text-white rounded-xl mt-5 px-4 py-2 hover:bg-slate-300"><a href="/">bakal balik ke home</a></button>

                    <button className="bg-black text-white rounded-xl mt-5 px-4 py-2 hover:bg-slate-300"><a href="/product">ke produk nih</a></button>
                  </NavigationMenuItem>
                </NavigationMenuList>
              </NavigationMenu>
            </nav>
          </SheetContent>
        </Sheet>
        <ModeToggle />
      </div>
    </header>
  );
}

function MenuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}
